metadata:
  name: 'lms-site'
  namespace: 'smartclass'

replicas:
  count: 1
  revisionHistoryLimit: 0

image:
  version: main-3fa92f3
  repository: 142373294051.dkr.ecr.us-east-1.amazonaws.com/lms-site
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
