metadata:
  name: 'lms-site'
  namespace: 'smartclass'

replicas:
  count: 1
  revisionHistoryLimit: 0

image:
  version: main-afa25ff
  repository: 142373294051.dkr.ecr.us-east-1.amazonaws.com/frontend
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
