# Default values for front-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: 'lms-site'
  namespace: 'smartclass'

replicas:
  count: 1
  revisionHistoryLimit: 0

image:
  version: main-722b669
  repository: 142373294051.dkr.ecr.us-east-1.amazonaws.com/lms-site
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  containerPort: 30000
